# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f116763f24e31651cea43f759ef23692a717fa7342b8750100c71b6236e53d568ec051c6ff94dcda003460484173b6b1bb5d6bdf09efa0da6d1c27813d84f14

test:
  secret_key_base: df6abb949ad0b69f43be93492f7193dcee939825dfd33e5b5a80f23ac94a4f9398bce7df17c87ccbd88bfb1fbe88902a06b1767bf4d81d10f28dfc7027f18257

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
